name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["", "--no-default-features"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install libseccomp-dev (for default features)
        if: matrix.features == ''
        run: |
          sudo apt-get update
          sudo apt-get install -y libseccomp-dev
      - run: cargo check ${{ matrix.features }}

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["", "--no-default-features"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install libseccomp-dev (for default features)
        if: matrix.features == ''
        run: |
          sudo apt-get update
          sudo apt-get install -y libseccomp-dev
      - run: cargo test ${{ matrix.features }}

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Install libseccomp-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y libseccomp-dev
      - run: cargo clippy -- -D warnings

  security_audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-audit
      - run: cargo audit

  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        target: 
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin
        exclude:
          - os: macos-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-unknown-linux-musl
          - os: macos-latest
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libseccomp-dev
          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu
          fi
          if [[ "${{ matrix.target }}" == "x86_64-unknown-linux-musl" ]]; then
            sudo apt-get install -y musl-tools
          fi
          
      - name: Build
        run: |
          if [[ "${{ matrix.target }}" == *"linux"* ]]; then
            if [[ "${{ matrix.target }}" == "x86_64-unknown-linux-musl" ]]; then
              # Build musl target without seccomp for better static linking compatibility
              cargo build --release --target ${{ matrix.target }} --no-default-features
            else
              cargo build --release --target ${{ matrix.target }}
            fi
          else
            cargo build --release --target ${{ matrix.target }} --no-default-features
          fi
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: capsule-run-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/capsule-run*

  test-macos:
    name: Test macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Check compilation
        run: cargo check --no-default-features
      - name: Run tests
        run: cargo test --no-default-features
      - name: Check formatting
        run: cargo fmt --all -- --check